openapi: 3.0.1
info:
  title: Bank Star Recommendation API
  version: 1.0.0

paths:
  /recommendation/{user_id}:
    get:
      summary: Get recommendations
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Recommendations list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecommendationResponse'

components:
  schemas:
    RecommendationResponse:
      type: object
      properties:
        user_id:
          type: string
        recommendations:
          type: array
          items:
            $ref: '#/components/schemas/Recommendation'
    Recommendation:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        text:
          type: string