spring.application.name=bank
application.recommendations-db.url=jdbc:h2:file:./transaction

telegram.bot.token=8486182418:AAG2kv2sLO3xl5YLs7zaSN73zqdPECsZ4Wo

spring.datasource.url= jdbc:postgresql://localhost:5432/Bank
spring.datasource.username= myUser
spring.datasource.password= 141219
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

spring.liquibase.enabled= true

## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto= validate
#spring.jpa.show-sql=true