-- liquibase formatted sql

-- changeset euzhastina:1
CREATE TABLE dynamic_recommendations (
id UUID PRIMARY KEY,
product_name VARCHAR(255),
product_id UUID,
product_text TEXT
);

CREATE TABLE dynamic_rules (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
dynamic_recommendation_id UUID,
query VARCHAR(255),
negate BOOLEAN default false,
CONSTRAINT fk_dynamic_rules_dynamic_recommendations
FOREIGN KEY (dynamic_recommendation_id)
REFERENCES dynamic_recommendations (id)
ON DELETE CASCADE
);

CREATE TABLE arguments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
dynamic_rule_id BIGINT,
product_type VARCHAR(255),
transaction_type VARCHAR(255),
math_sign VARCHAR(255),
threshold_sum INTEGER CHECK (threshold_sum >= 0),
CONSTRAINT fk_arguments_dynamic_rules
FOREIGN KEY (dynamic_rule_id)
REFERENCES dynamic_rules (id)
ON DELETE CASCADE
);
